### ISSUE TITLE
Not working for macOS project on macOS Sierra

### ISSUE THREAD

**Issue by JohnCoates** [codecov/example-swift#15] opened 2016-09-23 09:13 UTC
I'm trying to add codecov support to my project [Aerial](http://github.com/johncoates/aerial), but I get non-stop issues when I try using a project that targets macOS, and it's working fine on iOS targeting projects.

Using Xcode 8 GM on macOS Sierra GM.

I've attached an example project (made from the default Xcode template). run.sh contains the commands I run, which for reference are:
````
-scheme CoverageTest -sdk macosx10.12 -destination 'platform=OS X,arch=x86_64' build test
bash <(curl -s https://codecov.io/bash) -J 'CoverageTest'
````
Attached: [CoverageTest.zip](https://github.com/codecov/example-swift/files/489239/CoverageTest.zip)

output:
````

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-e7c0c15


x> No CI provider detected.
    project root: .
/dev/fd/63: line 656: hg: command not found
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
==> Processing XCode reports
    DerivedData folder: /Users/macbook/Library/Developer/Xcode/DerivedData
    + Building reports for CoverageTest app
error: Failed to load coverage: No such file or directory
    x> llvm-cov failed to produce results for /Users/macbook/Library/Developer/Xcode/DerivedData/CoverageTest-ayervtxybetyfudczfbitqwlrnje/Build/Intermediates/CodeCoverage/Products/Debug/CoverageTest.app/CoverageTest
    + Building reports for CoverageTestTests xctest
error: Failed to load coverage: No such file or directory
    x> llvm-cov failed to produce results for /Users/macbook/Library/Developer/Xcode/DerivedData/CoverageTest-ayervtxybetyfudczfbitqwlrnje/Build/Intermediates/CodeCoverage/Products/Debug/CoverageTest.app/Contents/PlugIns/CoverageTestTests.xctest/CoverageTestTests
    -> Running gcov for Obj-C
==> Running gcov in . (disable via -X gcov)
==> Searching for coverage reports in:
    + .
    -> Found 2 reports
==> Python coveragepy not found
==> Detecting git/mercurial file structure
==> Reading reports
    - Skipping empty file ./CoverageTest.app.coverage.txt
    - Skipping empty file ./CoverageTestTests.xctest.coverage.txt
--> No coverage data found.
    Please visit http://docs.codecov.io/docs/supported-languages
    search for your projects language to learn how to collect reports.
````

**Comment by stevepeak** [comment] 2016-09-23 13:09
Hey @JohnCoates. This may be related to https://github.com/codecov/codecov-bash/pull/33

Thoughts?

**Comment by stevepeak** [comment] 2016-09-23 13:11
What does your DerivedData folder looks like?

```
ls -al /Users/macbook/Library/Developer/Xcode/DerivedData
```

**Comment by JohnCoates** [comment] 2016-09-23 20:02
Yeah, it's probably related to that. Do you know of any Mac-only projects on Github using codecov? This is on a completely clean install of Sierra btw.

Running that command outputs: 
````
ls -al /Users/macbook/Library/Developer/Xcode/DerivedData
total 16
drwxr-xr-x   5 macbook  staff   170 Sep 23 12:58 .
drwxr-xr-x  12 macbook  staff   408 Sep 23 03:46 ..
-rw-r--r--@  1 macbook  staff  6148 Sep 22 23:22 .DS_Store
drwxr-xr-x@  5 macbook  staff   170 Sep 23 12:59 CoverageTest-ayervtxybetyfudczfbitqwlrnje
drwxr-xr-x@  5 macbook  staff   170 Sep 23 12:59 ModuleCache
````

**Comment by JohnCoates** [comment] 2016-09-23 20:07
Here's a full tree output in case the folder structure is different
````
tree ~/Library/Developer/Xcode/DerivedData 
/Users/macbook/Library/Developer/Xcode/DerivedData
└── CoverageTest-ayervtxybetyfudczfbitqwlrnje
    ├── Build
    │   ├── Intermediates
    │   │   ├── CodeCoverage
    │   │   │   ├── Coverage.profdata
    │   │   │   ├── Intermediates
    │   │   │   │   └── CoverageTest.build
    │   │   │   │       └── Debug
    │   │   │   │           ├── CoverageTest.build
    │   │   │   │           │   ├── CoverageTest-all-non-framework-target-headers.hmap
    │   │   │   │           │   ├── CoverageTest-all-target-headers.hmap
    │   │   │   │           │   ├── CoverageTest-generated-files.hmap
    │   │   │   │           │   ├── CoverageTest-own-target-headers.hmap
    │   │   │   │           │   ├── CoverageTest-project-headers.hmap
    │   │   │   │           │   ├── CoverageTest.hmap
    │   │   │   │           │   ├── DerivedSources
    │   │   │   │           │   │   └── CoverageTest-Swift.h
    │   │   │   │           │   ├── MainMenu-PartialInfo.plist
    │   │   │   │           │   ├── Objects-normal
    │   │   │   │           │   │   └── x86_64
    │   │   │   │           │   │       ├── AppDelegate.d
    │   │   │   │           │   │       ├── AppDelegate.dia
    │   │   │   │           │   │       ├── AppDelegate.o
    │   │   │   │           │   │       ├── AppDelegate.swiftdeps
    │   │   │   │           │   │       ├── AppDelegate~partial.swiftdoc
    │   │   │   │           │   │       ├── AppDelegate~partial.swiftmodule
    │   │   │   │           │   │       ├── CoverageTest-OutputFileMap.json
    │   │   │   │           │   │       ├── CoverageTest-Swift.h
    │   │   │   │           │   │       ├── CoverageTest-master.swiftdeps
    │   │   │   │           │   │       ├── CoverageTest.LinkFileList
    │   │   │   │           │   │       ├── CoverageTest.swiftdoc
    │   │   │   │           │   │       ├── CoverageTest.swiftmodule
    │   │   │   │           │   │       └── CoverageTest_dependency_info.dat
    │   │   │   │           │   ├── assetcatalog_dependencies
    │   │   │   │           │   ├── assetcatalog_generated_info.plist
    │   │   │   │           │   ├── dgph
    │   │   │   │           │   ├── dgph~
    │   │   │   │           │   └── swift-overrides.hmap
    │   │   │   │           └── CoverageTestTests.build
    │   │   │   │               ├── CoverageTestTests-all-non-framework-target-headers.hmap
    │   │   │   │               ├── CoverageTestTests-all-target-headers.hmap
    │   │   │   │               ├── CoverageTestTests-generated-files.hmap
    │   │   │   │               ├── CoverageTestTests-own-target-headers.hmap
    │   │   │   │               ├── CoverageTestTests-project-headers.hmap
    │   │   │   │               ├── CoverageTestTests.hmap
    │   │   │   │               ├── DerivedSources
    │   │   │   │               │   └── CoverageTestTests-Swift.h
    │   │   │   │               ├── Objects-normal
    │   │   │   │               │   └── x86_64
    │   │   │   │               │       ├── CoverageTestTests-OutputFileMap.json
    │   │   │   │               │       ├── CoverageTestTests-Swift.h
    │   │   │   │               │       ├── CoverageTestTests-master.swiftdeps
    │   │   │   │               │       ├── CoverageTestTests.LinkFileList
    │   │   │   │               │       ├── CoverageTestTests.d
    │   │   │   │               │       ├── CoverageTestTests.dia
    │   │   │   │               │       ├── CoverageTestTests.o
    │   │   │   │               │       ├── CoverageTestTests.swiftdeps
    │   │   │   │               │       ├── CoverageTestTests.swiftdoc
    │   │   │   │               │       ├── CoverageTestTests.swiftmodule
    │   │   │   │               │       ├── CoverageTestTests_dependency_info.dat
    │   │   │   │               │       ├── CoverageTestTests~partial.swiftdoc
    │   │   │   │               │       └── CoverageTestTests~partial.swiftmodule
    │   │   │   │               ├── dgph
    │   │   │   │               ├── dgph~
    │   │   │   │               └── swift-overrides.hmap
    │   │   │   ├── Products
    │   │   │   │   └── Debug
    │   │   │   │       ├── CoverageTest.app
    │   │   │   │       │   └── Contents
    │   │   │   │       │       ├── Frameworks
    │   │   │   │       │       │   ├── IDEBundleInjection.framework
    │   │   │   │       │       │   │   ├── IDEBundleInjection -> Versions/Current/IDEBundleInjection
    │   │   │   │       │       │   │   ├── Resources -> Versions/Current/Resources
    │   │   │   │       │       │   │   └── Versions
    │   │   │   │       │       │   │       ├── A
    │   │   │   │       │       │   │       │   ├── IDEBundleInjection
    │   │   │   │       │       │   │       │   ├── Resources
    │   │   │   │       │       │   │       │   │   ├── Info.plist
    │   │   │   │       │       │   │       │   │   └── version.plist
    │   │   │   │       │       │   │       │   └── _CodeSignature
    │   │   │   │       │       │   │       │       └── CodeResources
    │   │   │   │       │       │   │       └── Current -> A
    │   │   │   │       │       │   ├── XCTest.framework
    │   │   │   │       │       │   │   ├── Headers -> Versions/Current/Headers
    │   │   │   │       │       │   │   ├── Modules -> Versions/Current/Modules
    │   │   │   │       │       │   │   ├── Resources -> Versions/Current/Resources
    │   │   │   │       │       │   │   ├── Versions
    │   │   │   │       │       │   │   │   ├── A
    │   │   │   │       │       │   │   │   │   ├── Headers
    │   │   │   │       │       │   │   │   │   │   ├── XCAbstractTest.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTest.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestAssertions.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestAssertionsImpl.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestCase+AsynchronousTesting.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestCase.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestCaseRun.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestDefines.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestErrors.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestExpectation.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestLog.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestObservation.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestObservationCenter.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestObserver.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestProbe.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestRun.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestSuite.h
    │   │   │   │       │       │   │   │   │   │   ├── XCTestSuiteRun.h
    │   │   │   │       │       │   │   │   │   │   ├── XCUIApplication.h
    │   │   │   │       │       │   │   │   │   │   ├── XCUICoordinate.h
    │   │   │   │       │       │   │   │   │   │   ├── XCUIDevice.h
    │   │   │   │       │       │   │   │   │   │   ├── XCUIElement.h
    │   │   │   │       │       │   │   │   │   │   ├── XCUIElementAttributes.h
    │   │   │   │       │       │   │   │   │   │   ├── XCUIElementQuery.h
    │   │   │   │       │       │   │   │   │   │   ├── XCUIElementTypeQueryProvider.h
    │   │   │   │       │       │   │   │   │   │   ├── XCUIElementTypes.h
    │   │   │   │       │       │   │   │   │   │   ├── XCUIKeyboardKeys.h
    │   │   │   │       │       │   │   │   │   │   └── XCUIRemote.h
    │   │   │   │       │       │   │   │   │   ├── Modules
    │   │   │   │       │       │   │   │   │   │   └── module.modulemap
    │   │   │   │       │       │   │   │   │   ├── Resources
    │   │   │   │       │       │   │   │   │   │   ├── Info.plist
    │   │   │   │       │       │   │   │   │   │   ├── en.lproj
    │   │   │   │       │       │   │   │   │   │   │   └── InfoPlist.strings
    │   │   │   │       │       │   │   │   │   │   └── version.plist
    │   │   │   │       │       │   │   │   │   ├── TextBasedStubs
    │   │   │   │       │       │   │   │   │   │   └── XCTest.tbd
    │   │   │   │       │       │   │   │   │   ├── XCTest
    │   │   │   │       │       │   │   │   │   ├── XCTest.tbd -> TextBasedStubs/XCTest.tbd
    │   │   │   │       │       │   │   │   │   ├── XPCServices
    │   │   │   │       │       │   │   │   │   │   ├── XCUIRecorderService.xpc
    │   │   │   │       │       │   │   │   │   │   │   └── Contents
    │   │   │   │       │       │   │   │   │   │   │       ├── Info.plist
    │   │   │   │       │       │   │   │   │   │   │       ├── MacOS
    │   │   │   │       │       │   │   │   │   │   │       │   └── XCUIRecorderService
    │   │   │   │       │       │   │   │   │   │   │       ├── _CodeSignature
    │   │   │   │       │       │   │   │   │   │   │       │   └── CodeResources
    │   │   │   │       │       │   │   │   │   │   │       └── version.plist
    │   │   │   │       │       │   │   │   │   │   └── xctestSymbolicator.xpc
    │   │   │   │       │       │   │   │   │   │       └── Contents
    │   │   │   │       │       │   │   │   │   │           ├── Info.plist
    │   │   │   │       │       │   │   │   │   │           ├── MacOS
    │   │   │   │       │       │   │   │   │   │           │   └── xctestSymbolicator
    │   │   │   │       │       │   │   │   │   │           ├── _CodeSignature
    │   │   │   │       │       │   │   │   │   │           │   └── CodeResources
    │   │   │   │       │       │   │   │   │   │           └── version.plist
    │   │   │   │       │       │   │   │   │   └── _CodeSignature
    │   │   │   │       │       │   │   │   │       └── CodeResources
    │   │   │   │       │       │   │   │   └── Current -> A
    │   │   │   │       │       │   │   ├── XCTest -> Versions/Current/XCTest
    │   │   │   │       │       │   │   ├── XCTest.tbd -> Versions/Current/XCTest.tbd
    │   │   │   │       │       │   │   └── XPCServices -> Versions/Current/XPCServices
    │   │   │   │       │       │   ├── libswiftAppKit.dylib
    │   │   │   │       │       │   ├── libswiftCore.dylib
    │   │   │   │       │       │   ├── libswiftCoreData.dylib
    │   │   │   │       │       │   ├── libswiftCoreGraphics.dylib
    │   │   │   │       │       │   ├── libswiftCoreImage.dylib
    │   │   │   │       │       │   ├── libswiftDarwin.dylib
    │   │   │   │       │       │   ├── libswiftDispatch.dylib
    │   │   │   │       │       │   ├── libswiftFoundation.dylib
    │   │   │   │       │       │   ├── libswiftIOKit.dylib
    │   │   │   │       │       │   ├── libswiftObjectiveC.dylib
    │   │   │   │       │       │   ├── libswiftXPC.dylib
    │   │   │   │       │       │   └── libswiftos.dylib
    │   │   │   │       │       ├── Info.plist
    │   │   │   │       │       ├── MacOS
    │   │   │   │       │       │   └── CoverageTest
    │   │   │   │       │       ├── PkgInfo
    │   │   │   │       │       ├── PlugIns
    │   │   │   │       │       │   └── CoverageTestTests.xctest
    │   │   │   │       │       │       └── Contents
    │   │   │   │       │       │           ├── Frameworks
    │   │   │   │       │       │           │   ├── libswiftAppKit.dylib
    │   │   │   │       │       │           │   ├── libswiftCore.dylib
    │   │   │   │       │       │           │   ├── libswiftCoreData.dylib
    │   │   │   │       │       │           │   ├── libswiftCoreGraphics.dylib
    │   │   │   │       │       │           │   ├── libswiftCoreImage.dylib
    │   │   │   │       │       │           │   ├── libswiftDarwin.dylib
    │   │   │   │       │       │           │   ├── libswiftDispatch.dylib
    │   │   │   │       │       │           │   ├── libswiftFoundation.dylib
    │   │   │   │       │       │           │   ├── libswiftIOKit.dylib
    │   │   │   │       │       │           │   ├── libswiftObjectiveC.dylib
    │   │   │   │       │       │           │   ├── libswiftXCTest.dylib
    │   │   │   │       │       │           │   ├── libswiftXPC.dylib
    │   │   │   │       │       │           │   └── libswiftos.dylib
    │   │   │   │       │       │           ├── Info.plist
    │   │   │   │       │       │           ├── MacOS
    │   │   │   │       │       │           │   └── CoverageTestTests
    │   │   │   │       │       │           ├── Resources
    │   │   │   │       │       │           │   └── libswiftRemoteMirror.dylib
    │   │   │   │       │       │           └── _CodeSignature
    │   │   │   │       │       │               └── CodeResources
    │   │   │   │       │       ├── Resources
    │   │   │   │       │       │   ├── Base.lproj
    │   │   │   │       │       │   │   └── MainMenu.nib
    │   │   │   │       │       │   └── libswiftRemoteMirror.dylib
    │   │   │   │       │       └── _CodeSignature
    │   │   │   │       │           └── CodeResources
    │   │   │   │       ├── CoverageTest.swiftmodule
    │   │   │   │       │   ├── x86_64.swiftdoc
    │   │   │   │       │   └── x86_64.swiftmodule
    │   │   │   │       └── CoverageTestTests.swiftmodule
    │   │   │   │           ├── x86_64.swiftdoc
    │   │   │   │           └── x86_64.swiftmodule
    │   │   │   └── ProfileData
    │   │   │       └── 39259.profraw
    │   │   └── CoverageTest.build
    │   │       └── Debug
    │   │           └── CoverageTest.build
    │   │               ├── CoverageTest-all-non-framework-target-headers.hmap
    │   │               ├── CoverageTest-all-target-headers.hmap
    │   │               ├── CoverageTest-generated-files.hmap
    │   │               ├── CoverageTest-own-target-headers.hmap
    │   │               ├── CoverageTest-project-headers.hmap
    │   │               ├── CoverageTest.hmap
    │   │               ├── DerivedSources
    │   │               │   └── CoverageTest-Swift.h
    │   │               ├── MainMenu-PartialInfo.plist
    │   │               ├── Objects-normal
    │   │               │   └── x86_64
    │   │               │       ├── AppDelegate.d
    │   │               │       ├── AppDelegate.dia
    │   │               │       ├── AppDelegate.o
    │   │               │       ├── AppDelegate.swiftdeps
    │   │               │       ├── AppDelegate~partial.swiftdoc
    │   │               │       ├── AppDelegate~partial.swiftmodule
    │   │               │       ├── CoverageTest-OutputFileMap.json
    │   │               │       ├── CoverageTest-Swift.h
    │   │               │       ├── CoverageTest-master.swiftdeps
    │   │               │       ├── CoverageTest.LinkFileList
    │   │               │       ├── CoverageTest.swiftdoc
    │   │               │       ├── CoverageTest.swiftmodule
    │   │               │       └── CoverageTest_dependency_info.dat
    │   │               ├── assetcatalog_dependencies
    │   │               ├── assetcatalog_generated_info.plist
    │   │               ├── dgph
    │   │               ├── dgph~
    │   │               └── swift-overrides.hmap
    │   └── Products
    │       └── Debug
    │           ├── CoverageTest.app
    │           │   └── Contents
    │           │       ├── Frameworks
    │           │       │   ├── libswiftAppKit.dylib
    │           │       │   ├── libswiftCore.dylib
    │           │       │   ├── libswiftCoreData.dylib
    │           │       │   ├── libswiftCoreGraphics.dylib
    │           │       │   ├── libswiftCoreImage.dylib
    │           │       │   ├── libswiftDarwin.dylib
    │           │       │   ├── libswiftDispatch.dylib
    │           │       │   ├── libswiftFoundation.dylib
    │           │       │   ├── libswiftIOKit.dylib
    │           │       │   ├── libswiftObjectiveC.dylib
    │           │       │   ├── libswiftXPC.dylib
    │           │       │   └── libswiftos.dylib
    │           │       ├── Info.plist
    │           │       ├── MacOS
    │           │       │   └── CoverageTest
    │           │       ├── PkgInfo
    │           │       ├── Resources
    │           │       │   ├── Base.lproj
    │           │       │   │   └── MainMenu.nib
    │           │       │   └── libswiftRemoteMirror.dylib
    │           │       └── _CodeSignature
    │           │           └── CodeResources
    │           └── CoverageTest.swiftmodule
    │               ├── x86_64.swiftdoc
    │               └── x86_64.swiftmodule
    ├── Logs
    │   ├── Build
    │   │   ├── 33467721-8F94-4A19-A8AF-142E5E0E659A.xcactivitylog
    │   │   ├── 6D7E39BE-FA6A-4D5B-B4E8-795326672DD6.xcactivitylog
    │   │   ├── Cache.db
    │   │   └── EFC50754-C124-4780-A604-1BD9AA4A6906.xcactivitylog
    │   └── Test
    │       ├── 164FEDF5-A20C-408F-AAAE-1A52CA0C8DDA
    │       │   └── Session-CoverageTestTests-2016-09-23_125904-QTrFII.log
    │       ├── 164FEDF5-A20C-408F-AAAE-1A52CA0C8DDA.xcactivitylog
    │       ├── 164FEDF5-A20C-408F-AAAE-1A52CA0C8DDA.xccoverage
    │       ├── 164FEDF5-A20C-408F-AAAE-1A52CA0C8DDA_TestSummaries.plist
    │       ├── Attachments
    │       ├── B1A91C17-B13B-4BA0-9587-82C8685A7945
    │       │   └── Session-CoverageTestTests-2016-09-23_130430-wet20z.log
    │       ├── B1A91C17-B13B-4BA0-9587-82C8685A7945.xcactivitylog
    │       ├── B1A91C17-B13B-4BA0-9587-82C8685A7945.xccoverage
    │       ├── B1A91C17-B13B-4BA0-9587-82C8685A7945_TestSummaries.plist
    │       └── Cache.db
    └── info.plist

86 directories, 201 files
````

**Comment by stevepeak** [comment] 2016-09-23 21:40
Hum...Not sure what to say... You can try manually calling llvm-cov but you'll get the same results.

```
xcrun llvm-cov show -instr-profile "~/Library/Developer/Xcode/DerivedData " "~/Library/Developer/Xcode/DerivedData /CoverageTest-ayervtxybetyfudczfbitqwlrnje"
```

**Comment by JohnCoates** [comment] 2016-09-25 21:42
You're right, that command doesn't work.

This one does output the listings though:
`xcrun llvm-cov show -instr-profile ~/Library/Developer/Xcode/DerivedData/CoverageTest-ayervtxybetyfudczfbitqwlrnje/Build/Intermediates/CodeCoverage/Coverage.profdata ~/Library/Developer/Xcode/DerivedData/CoverageTest-ayervtxybetyfudczfbitqwlrnje/Build/Intermediates/CodeCoverage/Products/Debug/CoverageTest.app/Contents/MacOS/CoverageTest`

**Comment by stevepeak** [comment] 2016-09-26 11:32
What output do you get from executing the above command?

**Comment by JohnCoates** [comment] 2016-09-26 20:05
I get this:

````
/Users/macbook/Dev/Sandbox/CoverageTest/CoverageTest/AppDelegate.swift:
       |    1|//
       |    2|//  AppDelegate.swift
       |    3|//  CoverageTest
       |    4|//
       |    5|//  Created by John Coates on 9/23/16.
       |    6|//  Copyright © 2016 John Coates. All rights reserved.
       |    7|//
       |    8|
       |    9|import Cocoa
       |   10|
       |   11|@NSApplicationMain
       |   12|class AppDelegate: NSObject, NSApplicationDelegate {
       |   13|
       |   14|    @IBOutlet weak var window: NSWindow!
       |   15|
       |   16|
      1|   17|    func applicationDidFinishLaunching(_ aNotification: Notification) {
      1|   18|        // Insert code here to initialize your application
      1|   19|    }
       |   20|
      0|   21|    func applicationWillTerminate(_ aNotification: Notification) {
      0|   22|        // Insert code here to tear down your application
      0|   23|    }
       |   24|
       |   25|
       |   26|}
       |   27|
````

**Comment by stevepeak** [comment] 2016-09-29 20:03
@JohnCoates could you give this a shot to see if it fixes the issue here. Thank you so much!

```
bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/04845559fe1caefe990968cc9e3851573012b756/codecov) -vd
```
> `-vd` is debug mode

**Comment by stevepeak** [comment] 2016-09-29 20:59
Duplicate of https://github.com/codecov/codecov-bash/pull/33 Thanks!

**Closed by stevepeak** 2016-09-29 20:59 UTC

**Comment by JohnCoates** [comment] 2016-09-29 21:04
It worked! Results are now showing up on my Codecov dashboard. Thanks a lot Steve

**Comment by stevepeak** [comment] 2016-09-29 21:14
Awesome! I'll be deploying this update today.
